Feature[G-1] create and update links
FREELANCER-ANGEL-ABRAHAM/project-get-back-end pull request #1
Opened 2022-02-02 02:12 UTC by JuanLuisCapellan1

/ready

2022-02-03 00:49 UTC, JuanLuisCapellan1 commented
# Details

This pull request contains the Users and Links CRUD.  It contains five endpoints, these are:

_Users routes:_
- POST /api/login
- POST /api/register
- PATCH /api/change-password
- POST /api/refresh-token

_LInks routes:_
- GET /api/links
- POST /api/create-link
- PATCH /api/update-link
- POST /api/delete-link

# Testing

<!---------------------------------------------------->
<table>
  <thead>
    <tr>
      <th colspan="2">POST /api/login</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Description</th>
      <td>Logs the user in and returns both accessToken and refreshToken</td>
    </tr>
    <tr>
      <th>Body</th>
      <td>
Content Type: _application/json_ 
Fields:

- username: string

- password: string

</td>
    </tr>
    <tr>
      <th>Returns</th>
      <td>

Content Type: application/json
{
     "accessToken":  accessToken,
     "refreshToken":  refreshToken
}

</td>
    </tr>
  </tbody>
</table>

<!---------------------------------------------------->


<!---------------------------------------------------->
<table>
  <thead>
    <tr>
      <th colspan="2">POST /api/register</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Description</th>
      <td>Create a new user and return a message</td>
    </tr>
    <tr>
      <th>Body</th>
      <td>
Content Type: _application/json_

Fields:
- username: string
- password: string
- secret: string
</td>
    </tr>
    <tr>
      <th>Returns</th>
      <td>

Content Type: application/json

{
     message: string
}

</td>
    </tr>
  </tbody>
</table>

<!---------------------------------------------------->

<!---------------------------------------------------->

<table>
  <thead>
    <tr>
      <th colspan="2">PATCH /api/change-password</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Description</th>
      <td>Update field password user</td>
    </tr>
    <tr>
      <th>Headers</th>
      <td>
Authorization: Bearer {accessToken}
</td>
    </tr>
    <tr>
      <th>Body</th>
      <td>
Content Type: _application/json_

Fields:
- *username:* string
- *password:* string
- *secret:* string
</td>
    </tr>
    <tr>
      <th>Returns</th>
      <td>

Content Type: application/json

{
    "message":  string
}

</td>
    </tr>
  </tbody>
</table>

<!---------------------------------------------------->


<!---------------------------------------------------->
<table>
  <thead>
    <tr>
      <th colspan="2">POST /api/refresh-token</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Description</th>
      <td>Recieves a refreshToken and returns a new accessToken and refreshToken</td>
    </tr>
    <tr>
      <th>Headers</th>
      <td>
Authorization: Bearer {refreshToken}
</td>
    </tr>
    <tr>
      <th>Returns</th>
      <td>

Content Type: application/json

{
    "accessToken": accessToken,
    "refreshToken": refreshToken
}

</td>
    </tr>
  </tbody>
</table>

<!---------------------------------------------------->
<table>
  <thead>
    <tr>
      <th colspan="2">GET /api/links</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Description</th>
      <td>Returns all links paginate according with the provided status. _Default status:_ 'active' and the povided visibility._Default visibility:_ 'visible'</td>
    </tr>
<tr>
      <th>Headers</th>
      <td>Authorization: Bearer {refreshToken}</td>
    </tr>
    <tr>
      <th>Query</th>
      <td>
Content Type: _Query params_
Fields:

- visibility: string(Just 'visible' and 'hidden' visibility are valid for this endpoint)

</td>
    </tr>
    <tr>
      <th>Returns</th>
      <td>

Content Type: application/json (array of objects)
{
    "links": {
        "docs": [
            {
                "_id": "61f73953c8a8c4954d47a063",
                "name": "New Link",
                "title": "welcome",
                "description": "firts link",
                "btn_name": "Subscribete",
                "url": "sdsd.com",
                "image": "https://pablo-web-backend.s3.amazonaws.com/9444dea9-31af-44b2-8207-68aac4782ce6.png",
                "visibility": "hidden",
                "status": "active",
                "__v": 0
            },
            {
                "_id": "61fa8151882e95d5e1266471",
                "name": "New Link",
                "title": "welcome",
                "description": "firts link",
                "btn_name": "Subscribete",
                "url": "sdsd.com",
                "image": "https://pablo-web-backend.s3.amazonaws.com/9444dea9-31af-44b2-8207-68aac4782ce6.png",
                "visibility": "hidden",
                "status": "active",
                "__v": 0
            },
            {
                "_id": "61fa8164882e95d5e1266475",
                "name": "New Link",
                "title": "welcome",
                "description": "firts link",
                "btn_name": "Subscribete",
                "url": "sdsd.com",
                "image": "https://pablo-web-backend.s3.amazonaws.com/9444dea9-31af-44b2-8207-68aac4782ce6.png",
                "visibility": "hidden",
                "status": "active",
                "__v": 0
            },
            {
                "_id": "61fa8166882e95d5e1266476",
                "name": "New Link",
                "title": "welcome",
                "description": "firts link",
                "btn_name": "Subscribete",
                "url": "sdsd.com",
                "image": "https://pablo-web-backend.s3.amazonaws.com/9444dea9-31af-44b2-8207-68aac4782ce6.png",
                "visibility": "hidden",
                "status": "active",
                "__v": 0
            },
            {
                "_id": "61fa8168882e95d5e1266477",
                "name": "New Link",
                "title": "welcome",
                "description": "firts link",
                "btn_name": "Subscribete",
                "url": "sdsd.com",
                "image": "https://pablo-web-backend.s3.amazonaws.com/9444dea9-31af-44b2-8207-68aac4782ce6.png",
                "visibility": "hidden",
                "status": "active",
                "__v": 0
            },
            {
                "_id": "61fa816c882e95d5e1266478",
                "name": "New Link",
                "title": "welcome",
                "description": "firts link",
                "btn_name": "Subscribete",
                "url": "sdsd.com",
                "image": "https://pablo-web-backend.s3.amazonaws.com/9444dea9-31af-44b2-8207-68aac4782ce6.png",
                "visibility": "hidden",
                "status": "active",
                "__v": 0
            },
            {
                "_id": "61fa816f882e95d5e1266479",
                "name": "New Link",
                "title": "welcome",
                "description": "firts link",
                "btn_name": "Subscribete",
                "url": "sdsd.com",
                "image": "https://pablo-web-backend.s3.amazonaws.com/9444dea9-31af-44b2-8207-68aac4782ce6.png",
                "visibility": "hidden",
                "status": "active",
                "__v": 0
            }
        ],
        "totalDocs": 7,
        "offset": 0,
        "limit": 10,
        "totalPages": 1,
        "page": 1,
        "pagingCounter": 1,
        "hasPrevPage": false,
        "hasNextPage": false,
        "prevPage": null,
        "nextPage": null
    }
}

</td>
    </tr>
  </tbody>
</table>

<!---------------------------------------------------->
<!---------------------------------------------------->
<table>
  <thead>
    <tr>
      <th colspan="2">POST /api/create-link</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Description</th>
      <td>Creates a new link</td>
    </tr>
    <tr>
      <th>Headers</th>
      <td>
Authorization: Bearer {refreshToken}
</td>
    </tr>
<tr>
      <th>Body</th>
      <td>
Content Type: _multipart/form-data_

Fields:

- name: string
- title: string
- description: string
- btn_name: string
- url: string
- image: file
- visibility: string (Just 'visible' an [...]

2022-02-04 20:41 UTC, KingAzizz requested changes

2022-02-04 20:41 UTC, KingAzizz commented on src/app.js
> +);
add new line

2022-02-04 20:41 UTC, KingAzizz commented on src/database.js
> -module.exports = { connect, };
add new line

2022-02-04 20:41 UTC, KingAzizz commented on src/config.js
> +}
add new line

2022-02-16 04:03 UTC, angelabrahannunez approved these changes
Excellent!

2022-02-16 04:04 UTC, merged